package mail

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	dkimKeysDir     = "/etc/opendkim/userkeys"
	dkimSigningTable = "/etc/opendkim/SigningTable"
	dkimKeyTable     = "/etc/opendkim/KeyTable"
	dkimSelector    = "default"
)

// GenerateDKIMKey generates a 2048-bit DKIM key for the domain,
// updates OpenDKIM tables, and returns the public key value for DNS.
func GenerateDKIMKey(domain string) (string, error) {
	keyDir := filepath.Join(dkimKeysDir, domain)
	if err := os.MkdirAll(keyDir, 0700); err != nil {
		return "", fmt.Errorf("mkdir dkim: %w", err)
	}

	// Generate key — always 2048-bit
	cmd := exec.Command("opendkim-genkey",
		"-b", "2048",
		"-d", domain,
		"-D", keyDir,
		"-s", dkimSelector,
		"-v",
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("opendkim-genkey: %w\n%s", err, string(out))
	}

	// Fix ownership
	exec.Command("chown", "-R", "opendkim:opendkim", keyDir).Run()
	exec.Command("chmod", "600", filepath.Join(keyDir, dkimSelector+".private")).Run()

	// Read public key from .txt file generated by opendkim-genkey
	pubKeyPath := filepath.Join(keyDir, dkimSelector+".txt")
	pubKeyRaw, err := os.ReadFile(pubKeyPath)
	if err != nil {
		return "", fmt.Errorf("read pubkey: %w", err)
	}
	pubKeyValue := parseDKIMPublicKey(string(pubKeyRaw))

	// Update KeyTable: selector._domainkey.domain domain:selector:/path/to/private
	keyTableEntry := fmt.Sprintf(
		"%s._domainkey.%s %s:%s:%s",
		dkimSelector, domain, domain, dkimSelector,
		filepath.Join(keyDir, dkimSelector+".private"),
	)
	updateDKIMTable(dkimKeyTable, domain, keyTableEntry)

	// Update SigningTable: *@domain selector._domainkey.domain
	signingEntry := fmt.Sprintf("*@%s %s._domainkey.%s", domain, dkimSelector, domain)
	updateDKIMTable(dkimSigningTable, domain, signingEntry)

	// Reload OpenDKIM
	exec.Command("systemctl", "reload", "opendkim").Run()

	return pubKeyValue, nil
}

// RemoveDKIMKey removes the DKIM key and OpenDKIM table entries for a domain.
func RemoveDKIMKey(domain string) {
	removeDKIMTableEntry(dkimKeyTable, domain)
	removeDKIMTableEntry(dkimSigningTable, domain)
	os.RemoveAll(filepath.Join(dkimKeysDir, domain))
	exec.Command("systemctl", "reload", "opendkim").Run()
}

// updateDKIMTable replaces or appends an entry for the domain in an OpenDKIM table file.
func updateDKIMTable(path, domain, entry string) {
	content, _ := os.ReadFile(path)
	var kept []string
	for _, line := range strings.Split(string(content), "\n") {
		if line == "" {
			continue
		}
		// Remove existing entry for this domain
		if strings.Contains(line, domain) {
			continue
		}
		kept = append(kept, line)
	}
	kept = append(kept, entry)
	os.WriteFile(path, []byte(strings.Join(kept, "\n")+"\n"), 0644)
}

func removeDKIMTableEntry(path, domain string) {
	content, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var kept []string
	for _, line := range strings.Split(string(content), "\n") {
		if !strings.Contains(line, domain) {
			kept = append(kept, line)
		}
	}
	os.WriteFile(path, []byte(strings.Join(kept, "\n")), 0644)
}

// parseDKIMPublicKey extracts the p= value from an opendkim-genkey .txt file.
// The file looks like:
//   default._domainkey	IN	TXT	( "v=DKIM1; k=rsa; "
//           "p=MIIB..." )
func parseDKIMPublicKey(raw string) string {
	// Concatenate all quoted segments
	var sb strings.Builder
	inQuote := false
	for _, ch := range raw {
		switch ch {
		case '"':
			inQuote = !inQuote
		default:
			if inQuote {
				sb.WriteRune(ch)
			}
		}
	}
	return strings.TrimSpace(sb.String())
}
